--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TPEimperialPE/ViewDistance
build-by-default: true
branches:
- master
projects:
  ViewDistance:
    icon: "icon.png"
    path: ""
...
